env:
    global:
        - DOCKER_ENGINE_VERSION=1.12.3

before_install:
    # upgrade docker-engine to specific version
    - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_ENGINE_VERSION}-0~trusty
    - docker-compose --version

script:
    - docker pull shaunhanson/yahtzee_server
    - docker pull shaunhanson/yahtzee_client
    - ./build.sh
    - ./up.sh
    - sleep 5
    - ./run.sh
